version: "2"

run:
  timeout: 5m
  tests: false

linters:
  default: standard
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (net.Listener).Close
